### ISSUE TITLE
Reduce the default buffer size to 32 samples

### ISSUE THREAD

**Issue by unfa** [LMMS/zynaddsubfx#12]
ZynAddSubFX's default internal buffer size is 32 samples.

Becasue the LFOs and envelopes are updated only once for every buffer - this effectively changes the time resolution of these modules - they are not interpolated, so with big buffers we get stairstep-like functions. This is especially audible when synthesizing drums.

I think LMMS makes this buffer 512 samples - which gives plenty of stairsteps. I recently do a lot of ZynAddSUbFX syntheiss in Ardour nad I hear the difference clearly - Zyn sounds more "analog" there, and all sweeps are much smoother, especially when they are very fast.

Could this be fixed?

**Comment by Umcaruje** [comment]
LMMS internally uses a 256 buffer IIRC. I don't know a lot of machines that can handle 32 samples of latency on more complex projects though. I'm not an expert on this so I'll let someone else chime in as well

**Comment by tresf** [comment]
@JohannesLorenz can you help us classify this bug report?

**Comment by unfa** [comment]
I think that LMMS' internal buffer isn't related to ZynAddSubFX's internal buffer. I've read that someone has changed the Zyn buffer to 32 samples within LMMS code and it run fine.

**Comment by JohannesLorenz** [comment]
@tresf Sorry, but I don't know enough about this.

**Comment by tresf** [comment]
> I've read that someone has changed the Zyn buffer to 32 samples within LMMS code and it run fine.

Can you dig up some history on this or close the bug report please?  I can tag Mark as well, but I'd rather it's tracked in the official repo if that's the case.  It may also be obsoleted by https://github.com/LMMS/lmms/issues/4179.

**Comment by JohannesLorenz** [comment]
I asked Mark about it, he said that a smaller buffersize means that zyn updates its values more often (yes, I did not know this).

So I just tried out some things and there is a lot of difference between current zyn and the LMMS zyn. The buffersize could indeed be one reason. I would really like to try fixing this, even for 1.2, as it looks like a very easy fix and the sound quality really seems to get way better.

**Comment by unfa** [comment]
Reducing the Zyn buffer improves the sound especially for drums sounds where fast pitch envelopes are in use. But it also will improve any fast LFO sound.

**Comment by JohannesLorenz** [comment]
Doing a quick code reading, the zyn buffer size can be controlled using the "BUFFER SIZE" ruler in the LMMS options (as long as you are using the built-in zyn). I'm hearing significant differences for frequency modulated sounds when changing this slider (restarting is required).

The slider can be set down to 64. Editing your lmms RC file (on Linux ~/.lmmsrc.xml) you can set it down to 32.

@unfa What was your exact request?
1. Changing the buffersize for LMMS + all builtin plugins (including zyn)?
2. Changing the buffersize for zyn, but not for LMMS?

Option (2) seems to only make sense in case of CPU issues, I guess. Doing a few tries, I could not see any significant issues with 20 zyns in parallel.

**Comment by unfa** [comment]
I guess 64-sample buffer fro ZynAddSUbFX is already a huge improvement and should be sufficient.

I'm for increasing only Zyn's internal buffer, becasue it's affecting the sound quality. LMMS global buffer doens't have anything to do with it, so I'd leave it alone.

**Comment by JohannesLorenz** [comment]
Thanks @unfa . I still think that the LMMS UI should offer 32 sample buffers if the core allows it. Here's my suggestion:
* The UI fix to change the slider to a minimum to 32 samples is a nice beginner job. What about opening an issue (non 1.2.0, as it is not urgent) and tagging it as "good first issue"?
* Zyn itself has an issue with quick envelopes. You will hear clicks at the beginning and end if you set the buffer size to small values. We'll fix it over there very soon. I'm not sure if we should make the PR before 1.2.0.

**Comment by tresf** [comment]
Probably here: https://github.com/LMMS/lmms/blob/7c71bc657c34b2722f247e4820000c5e46f4d05f/src/gui/SetupDialog.cpp#L180-L185

**Comment by JohannesLorenz** [comment]
@tresf Exactly. I opened a new bug report [at LMMS](https://github.com/LMMS/lmms/issues/4305).

For the zyn issue, we now have a bug report [at the zyn issue tracker](https://sourceforge.net/p/zynaddsubfx/bugs/171/).

All in all, there is nothing left to do for *this* bug. Closing.
