### ISSUE TITLE
Stuck notes in mono/legato when receiving all-notes-off or the panic button.

### ISSUE THREAD

**Issue by caoliver** [LMMS/zynaddsubfx#5]
The note stack may maintain notes that haven't received note-off even if all-notes-off or the panic button is pressed.  Fix is:

```
diff --git a/src/Misc/Part.cpp b/src/Misc/Part.cpp
index 50d4ced..184a0e2 100644
--- a/src/Misc/Part.cpp
+++ b/src/Misc/Part.cpp
@@ -1020,6 +1020,7 @@ void Part::ComputePartSmps()
         killallnotes = 0;
         for(int nefx = 0; nefx < NUM_PART_EFX; ++nefx)
             partefx[nefx]->cleanup();
+        monomemnotes.clear();
     }
     ctl.updateportamento();
 }
```

This was also reported in LMMS/lmms.

**Comment by tresf** [comment]
This made it down. 
 Not sure when exactly, but it's your upstream commit. 
 Thanks, closing per https://github.com/LMMS/zynaddsubfx/commit/84f3e9406935b8389de2b87b1617792468dea1be.

> I must say that having two repos with the same code is a bit of a nightmare for a new comer.

Agreed.  Took us a few years, but we've fixed it via https://github.com/LMMS/lmms/pull/3930. 👍
