### ISSUE TITLE
Make every parameter automatable inside LMMS

### ISSUE THREAD

**Issue by unfa** [LMMS/zynaddsubfx#8]
Needless to say it'd square the awesomness of ZynAddSubFX.

I created a related issue in ZynAddSubFX dev tracker on SF:

https://sourceforge.net/p/zynaddsubfx/feature-requests/41/

Do you think this is possible?

**Comment by tresf** [comment]
@JohannesLorenz Should this be moved to https://github.com/LMMS/lmms/issues/4179?

**Comment by JohannesLorenz** [comment]
@tresf Not sure yet. Most of the stuff is missing on the LMMS side, but some stuff must be done on zyn aswell. This means DnD and a protocol for the DnD messages. We have a DnD issue report on zyn's bug tracker on SF. I'm fine closing it as a duplicate, but I leave the decision to you.

**Comment by tresf** [comment]
> I'm fine closing it as a duplicate, but I leave the decision to you.

It sounds like these efforts are being tracked elsewhere.  If LMMS is missing some stuff, we can track that in the LMMS repo, I feel.  👍

**Comment by fundamental** [comment]
What exactly is needed on Zyn's side? I was under the impression that DnD was working well enough that any further issues were on LMMS's side.

**Comment by tresf** [comment]
@fundamental yeah, good points.  I'll opened a new issue here: https://github.com/LMMS/lmms/issues/4263.
